version: '3.8'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: com.demo.neo4j:latest
    container_name: neo4j_connector_service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:7687
      - SPRING_DATA_NEO4J_DATABASE=neo4j
      - SPRING_DATA_NEO4J_USERNAME=neo4j
      - SPRING_DATA_NEO4J_PASSWORD=1234
    depends_on:
      - neo4j
    networks:
      - neo_net
    restart: always

  neo4j:
    image: neo4j:4.2.3-enterprise
    container_name: "neo4j-demo"
    volumes:
      - $HOME/graph_data/my_data:/data
      - $HOME/graph_data/my_data:/var/lib/neo4j/import
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/1234
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=true
      - apoc.export.file.enabled=true
      - apoc.export.json.all=true
      # Comment these lines if you do not have the memory available
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4j_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
    networks:
      - neo_net


networks:
  neo_net:
